-- ============================================================
-- 20260805190000_volledige_teamlijst.sql
-- Volledige teamlijst Feestweek 2026 (overschrijft bestaande teams)
-- ============================================================

delete from uitslagen;
delete from teams;

insert into teams (naam, categorie, volgorde) values
('Inteam', 'dames', 1),
('Vrijgezellig', 'heren', 1),
('Game Over', 'dames', 2),
('Trio Ome Loek', 'heren', 2),
('Nachtbrakers', 'heren', 3),
('Tuig van de Richel', 'heren', 4),
('Victorious Secret', 'dames', 3),
('Hot Stuff', 'dames', 4),
('Goud van Oud', 'heren', 5),
('The underdogs', 'heren', 6),
('Bier Bataven', 'heren', 7),
('Kater komt later', 'heren', 8),
('Hofdames', 'dames', 5),
('My home', 'dames', 6),
('Onze jongens uit 5huizen', 'heren', 9),
('De Voorstelling', 'heren', 10),
('Cheers', 'dames', 7),
('Menhunters', 'dames', 8),
('Onze jongens uit 5huizen', 'heren', 11),
('de kelderklasse', 'heren', 12),
('Simply The Best (STB)', 'dames', 9),
('Freddy''s Angels Never Alone', 'heren', 13),
('Hermanos', 'heren', 14),
('DSOF', 'dames', 10),
('''t Winckeltje', 'heren', 15),
('Echte Meisjes in Vijfhuizen', 'dames', 11),
('POLDERBOYS', 'heren', 16),
('De Pintewippers', 'heren', 17),
('Alleen maar Liefde', 'dames', 12),
('Alphalicious', 'dames', 13),
('WTF', 'dames', 14),
('Veni Vidi Vici Vijfhuizen', 'dames', 15),
('Lekker Gewoon', 'heren', 18),
('Wijnzinnig', 'dames', 16),
('Buurman & Buurman', 'heren', 19),
('Onderschatjes', 'dames', 17),
('Genieten', 'dames', 18),
('Biermusketiers', 'heren', 20),
('C''est la vie', 'dames', 19),
('Nooit meer naar huis', 'dames', 20),
('OnVoorStelBaar', 'dames', 21),
('Hofnarren', 'heren', 21),
('Niemand', 'dames', 22),
('On Point', 'dames', 23),
('de Spiering', 'dames', 24),
('Verenigde Chaos', 'dames', 25),
('Onno Jansen', 'heren', 22),
('Chickies op een Missie', 'dames', 26),
('AB normaal', 'heren', 23),
('De Vrienden Van', 'heren', 24),
('Prachtpatsers', 'dames', 27),
('High Five', 'dames', 28),
('Allstars', 'heren', 25),
('d''r op of d''r onder', 'dames', 29),
('De katers van morgen.....', 'dames', 30),
('Wat Nou?', 'heren', 26),
('Bende van Ellende', 'dames', 31),
('Fabulous Females', 'dames', 32),
('Goodlife', 'dames', 33),
('De Hoogste Tijd', 'dames', 34),
('Allergoeiste', 'heren', 27),
('Ladyjkillers', 'heren', 28),
('Tweede jeugd', 'heren', 29);
